project:
  type: default
  output-dir: _output
  preview:
    port: 4200
    browser: false
bibliography: references.bib
csl: ieee.csl
format:
  revealjs:
    slide-number: true
    theme: white
    logo: images/neu_logo.svg
    css: styles/styles.css
    highlight-style: atom-one
    fig-cap-location: bottom
    header-includes: <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
    include-in-header:
      text: |
        <script>
        MathJax = {
          loader: {
            load: ['[tex]/boldsymbol']
          },
          tex: {
            tags: "all",
            inlineMath: [['$','$'], ['\\(','\\)']],
            displayMath: [['$$','$$'], ['\\[','\\]']],
            processEscapes: true,
            processEnvironments: true,
            packages: {
              '[+]': ['boldsymbol']
            },
            macros: {
              mc: ["\\mathcal{#1}", 1],
              mb: ["\\mathbf{#1}", 1],
              nin: "n \\in \\mathcal{N}",
              bin: "b \\in \\mathcal{N}",
              kin: "k \\in \\mathcal{K}",
              jin: "j \\in \\mathcal{J}_n",
              kjin: "(k,j) \\in \\mathcal{B}_{n,i}",
              nbin: "(n,b) \\in \\mathcal{L}",
              knt: "\^k_n(t)",
              knjt: "\^k_{n_j}(t)",
              argmax: "\\mathop{\\mathrm{argmax}}",
              argmin: "\\mathop{\\mathrm{argmin}}",
            }
          }
        };
        </script>
        <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
mainfont: Lato
fig-cap-location: top
jupyter: python3
filters:
  - pseudocode